# Generated by Django 5.1.4 on 2024-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=20),
        ),
    ]
