# Generated by Django 5.1.4 on 2024-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_client_alter_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
